image: gitlab-registry.cern.ch/pseyfert/lxplus-like-dockerfile

before_script:
  - cd src

buildandrun:
  script:
    - make main
    - ./main

callgrind:
  script:
    - make
    - make profile
  artifacts:
    paths:
      - src/profile.out
